version: '3'

services:
  wordpress:
    image: wordpress:fpm-alpine
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - backend
      - frontend

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "30718030"
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - backend

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - frontend

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot -d example.com
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email youremail@example.com --agree-tos --no-eff-email --staging -d umaybatuhan
    depends_on:
      - nginx
    networks:
      - frontend


networks:
  frontend:
  backend:
